"use client";

import { useEffect, useRef, useState } from "react";
import { Play, Square } from "lucide-react";

export type Voice = {
  id: string;
  label: string;
  gender: "female" | "male";
  character: string;
  description: string;
};

/** Voice selector with an audio preview.
 *
 *  Previews are static files under public/voice-previews/, pregenerated by
 *  backend/scripts/pregenerate_voice_previews.py with the same accent steering
 *  a live session uses. The line and the voice list are both fixed, so calling
 *  Gemini on every click would spend seconds and money regenerating identical
 *  audio. Playback is instant.
 */
export function VoicePicker({
  voices,
  value,
  onChange,
}: {
  voices: Voice[];
  value: string;
  onChange: (voiceId: string) => void;
}) {
  const [playing, setPlaying] = useState(false);
  const [error, setError] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const selected = voices.find((v) => v.id === value);

  function stop() {
    audioRef.current?.pause();
    audioRef.current = null;
    setPlaying(false);
  }

  // Switching voice should not leave the previous one talking.
  useEffect(() => stop(), [value]);

  useEffect(() => () => audioRef.current?.pause(), []);

  function preview() {
    if (playing) {
      stop();
      return;
    }
    setError(false);
    const audio = new Audio(`/voice-previews/${value}.wav`);
    audio.onended = () => setPlaying(false);
    audio.onerror = () => {
      setError(true);
      setPlaying(false);
    };
    audioRef.current = audio;
    setPlaying(true);
    void audio.play().catch(() => {
      setError(true);
      setPlaying(false);
    });
  }

  return (
    <div>
      <div className="flex gap-2">
        <select
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="min-w-0 flex-1 rounded-md border bg-background px-2 py-1.5 text-sm"
          aria-label="Voice"
        >
          {voices.map((v) => (
            <option key={v.id} value={v.id}>
              {v.label} ({v.gender === "female" ? "female" : "male"})
            </option>
          ))}
        </select>
        <button
          type="button"
          onClick={preview}
          aria-label={playing ? "Stop preview" : `Play ${selected?.label ?? "voice"} preview`}
          className="flex h-9 w-9 shrink-0 cursor-pointer items-center justify-center rounded-md border transition-colors hover:bg-slate-50"
        >
          {playing ? (
            <Square className="h-3.5 w-3.5 fill-current" />
          ) : (
            <Play className="h-4 w-4" />
          )}
        </button>
      </div>
      <p className="mt-1.5 text-xs text-muted-foreground">
        {error ? (
          <span className="text-destructive">Could not play the preview. Try again.</span>
        ) : (
          selected?.description
        )}
      </p>
    </div>
  );
}
